apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
          - name: vol-1
            mountPath: /var/lib/postgresql/data
          # - name: vol-2
          #   mountPath: /data
        resources:
          requests: #LOAD and stress
            memory: "128Mi" # ~= 128MB
            cpu: "500m" # ~0.5G
          limits:
            memory: 512Mi
            cpu: 1000m
      volumes: # pod -> pvc
        - name: vol-1
          persistentVolumeClaim: 
            claimName: db-pvc