apiVersion: v1 # pods will always run on v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: default\
  labels:
    app: nginx
spec:
   containers:
     - name: nginx-contianer 
       image: nginx
       ports:
        - containerPort: 80