apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-python-job
spec:
  schedule: "* * * * *" # everymin
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: migration-job
            image: python-job:latest
            imagePullPolicy: Never
          restartPolicy: Never
